from django.urls import path
from . import views
urlpatterns = [
    path('',views.home, name="home"),
    path('chart',views.chart, name="chart"),
    path('User_count',views.get_data, name="UserCount"),
    path('get_data/cat',views.get_cat_data, name="getdatacat"),
    path('update_item/',views.updateItem, name=""),
    path('update_fav/',views.updateFav, name=""),
    path('detail/<int:product_id>/',views.details),
    path('cart',views.carts),
    path('checkout',views.checkout),
    path('contactus',views.contactus),
    path('favorite',views.favorite),
    path('profile',views.profile),
    path('about',views.about),
    path('status/<int:orderid>/',views.status,name="status"),
    path('payment',views.payment),
    path('complate',views.complate,name="sucess"),
    path('order/success/<int:id>/<str:trasection_id>',views.order_sucess,name="sucess"),
    path('order_details',views.order_details,name="order_details"),
    path('order_cancel/<int:id>',views.order_cancel,name="order_cancel"),
    path('order_cancel_details/<int:id>',views.order_cancel_details,name="order_cancel_details"),
    path('cstatus/<int:orderid>/',views.cstatus,name="cancelstatus"),
]
