# Generated by Django 4.0 on 2022-01-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=40)),
                ('address1', models.CharField(blank=True, max_length=60, null=True)),
                ('address2', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('phoneno', models.CharField(blank=True, max_length=10, null=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
