# Generated by Django 4.0.1 on 2022-02-22 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PROSSED', 'process'), ('SHIPING', 'shiping'), ('ONTHEWAY', 'ontheway'), ('RECIVED', 'receved')], default='PROSSED', max_length=9)),
                ('complate', models.BooleanField(default=False, null=True)),
                ('trasection_id', models.CharField(blank=True, max_length=100, null=True)),
                ('expectedtime', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customer')),
            ],
        ),
    ]
