# Generated by Django 4.0.1 on 2022-02-22 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cancelorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelorder',
            name='complate',
        ),
        migrations.RemoveField(
            model_name='cancelorder',
            name='status',
        ),
    ]
