# Generated by Django 4.0.1 on 2022-02-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_order_compete_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complate',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
