# Generated by Django 4.0.1 on 2022-01-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_witchlist_product_witchlistitemfield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WitchlistItemField',
            new_name='WitchlistItem',
        ),
    ]
