# Generated by Django 4.0.1 on 2022-02-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_order_complate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROSSED', 'process'), ('SHIPING', 'shiping'), ('ONTHEWAY', 'ontheway'), ('RECIVED', 'receved')], default=False, max_length=9),
        ),
    ]
