# Generated by Django 4.0.1 on 2022-01-21 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_witchlistitemfield_witchlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witchlist',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customer'),
        ),
        migrations.AlterField(
            model_name='witchlistitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product'),
        ),
        migrations.AlterField(
            model_name='witchlistitem',
            name='witchlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.witchlist'),
        ),
    ]
