# Generated by Django 4.0.2 on 2022-03-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_customer_address_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offerd_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
