# Generated by Django 4.0.1 on 2022-02-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expectedtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
