# Generated by Django 4.0.1 on 2022-02-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_customer_email_alter_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expectedtime',
            field=models.DateTimeField(null=True),
        ),
    ]
