# Generated by Django 4.0.2 on 2022-03-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_product_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complains',
            name='order',
        ),
    ]
