# Generated by Django 4.0.2 on 2022-03-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_product_available_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offerd_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
